/**/admittance_rcm_control:
  ros__parameters:
    base_link: "link_0"
    end_effector_link: "link_ee"
    f_ext_th: [2., 2., 2., 0.5, 0.5, 0.5]
    dq_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    dx_gains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
