joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
trajectory:
  type: effort_controllers/JointTrajectoryController
  joints:
    - A1
    - A2
    - A3
    - A4
    - A5
    - A6
    - A7
  gains:
    A1: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
    A2: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
    A3: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
    A4: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
    A5: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
    A6: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
    A7: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
