# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position controllers
PositionJointInterface_A1_controller:
  type: position_controllers/JointPositionController
  joint: joint_1

PositionJointInterface_A2_controller:
  type: position_controllers/JointPositionController
  joint: joint_2
  
PositionJointInterface_A3_controller:
  type: position_controllers/JointPositionController
  joint: joint_3
  
PositionJointInterface_A4_controller:
  type: position_controllers/JointPositionController
  joint: joint_4
  
PositionJointInterface_A5_controller:
  type: position_controllers/JointPositionController
  joint: joint_5
  
PositionJointInterface_A6_controller:
  type: position_controllers/JointPositionController
  joint: joint_6
  
PositionJointInterface_A7_controller:
  type: position_controllers/JointPositionController
  joint: joint_7

PositionJointInterface_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default

# Velocity controllers
VelocityJointInterface_A1_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_1

VelocityJointInterface_A2_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_2
  
VelocityJointInterface_A3_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_3
  
VelocityJointInterface_A4_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_4
  
VelocityJointInterface_A5_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_5
  
VelocityJointInterface_A6_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_6
  
VelocityJointInterface_A7_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_7

VelocityJointInterface_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: 
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default

