# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position controllers
PositionJointInterface_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - lbr_joint_1
    - lbr_joint_2
    - lbr_joint_3
    - lbr_joint_4
    - lbr_joint_5
    - lbr_joint_6
    - lbr_joint_7

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default
