# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  A1:
    has_velocity_limits: true
    max_velocity: 1.71042267
    has_acceleration_limits: false
    max_acceleration: 0
  A2:
    has_velocity_limits: true
    max_velocity: 1.71042267
    has_acceleration_limits: false
    max_acceleration: 0
  A3:
    has_velocity_limits: true
    max_velocity: 1.74532925
    has_acceleration_limits: false
    max_acceleration: 0
  A4:
    has_velocity_limits: true
    max_velocity: 2.26892803
    has_acceleration_limits: false
    max_acceleration: 0
  A5:
    has_velocity_limits: true
    max_velocity: 2.44346095
    has_acceleration_limits: false
    max_acceleration: 0
  A6:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0
  A7:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0