controller_names:
  - position_trajectory_controller

# http://control.ros.org/ros2_controllers/joint_trajectory_controller/doc/userdoc.html#ros2-interface-of-the-controller
position_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - lbr_A1
    - lbr_A2
    - lbr_A3
    - lbr_A4
    - lbr_A5
    - lbr_A6
    - lbr_A7
