controller_names:
  - joint_trajectory_controller

# http://control.ros.org/ros2_controllers/joint_trajectory_controller/doc/userdoc.html#ros2-interface-of-the-controller
joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - A1
    - A2
    - A3
    - A4
    - A5
    - A6
    - A7
