# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - A1
    - A2
    - A3
    - A4
    - A5
    - A6
    - A7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
lbr_control:
  type: position_controllers/JointPositionController
  joints:
    - A1
    - A2
    - A3
    - A4
    - A5
    - A6
    - A7
  gains:
    A1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    A2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    A3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    A4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    A5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    A6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    A7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1